### ISSUE TITLE
Error: Cannot find module 'laravel-elixir/tasks/shared/Tests'

### ISSUE THREAD

**Issue by LukeHowellDev** [JeffreyWay/laravel-elixir-codeception#7]
Receiving the following error when trying to run `gulp` or `gulp tdd` with `laravel-elixir-codeception` installed?

```
Error: Cannot find module 'laravel-elixir/tasks/shared/Tests'
```

Is this wrapper still functional or is there a better solution to using codeception and elixir together?

**Comment by rozklad** [comment]
This is probably caused by laravel-elixir update.

I've made a little workaround here https://github.com/rozklad/laravel-elixir-codeception-standalone

**Comment by LukeHowellDev** [comment]
Thanks.  This takes care of me for now.
